# Generated by Django 2.2.10 on 2021-10-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='surveys',
            new_name='survey',
        ),
    ]
